#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cua_Hang_Thu_Cung.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbWebsiteThuCung")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblAdmin(tblAdmin instance);
    partial void UpdatetblAdmin(tblAdmin instance);
    partial void DeletetblAdmin(tblAdmin instance);
    partial void InserttblUser(tblUser instance);
    partial void UpdatetblUser(tblUser instance);
    partial void DeletetblUser(tblUser instance);
    partial void InserttblBaiViet(tblBaiViet instance);
    partial void UpdatetblBaiViet(tblBaiViet instance);
    partial void DeletetblBaiViet(tblBaiViet instance);
    partial void InserttblChiTietDonHang(tblChiTietDonHang instance);
    partial void UpdatetblChiTietDonHang(tblChiTietDonHang instance);
    partial void DeletetblChiTietDonHang(tblChiTietDonHang instance);
    partial void InserttblDanhMuc(tblDanhMuc instance);
    partial void UpdatetblDanhMuc(tblDanhMuc instance);
    partial void DeletetblDanhMuc(tblDanhMuc instance);
    partial void InserttblDanhMucBaiViet(tblDanhMucBaiViet instance);
    partial void UpdatetblDanhMucBaiViet(tblDanhMucBaiViet instance);
    partial void DeletetblDanhMucBaiViet(tblDanhMucBaiViet instance);
    partial void InserttblDanhMucCha(tblDanhMucCha instance);
    partial void UpdatetblDanhMucCha(tblDanhMucCha instance);
    partial void DeletetblDanhMucCha(tblDanhMucCha instance);
    partial void InserttblDonHang(tblDonHang instance);
    partial void UpdatetblDonHang(tblDonHang instance);
    partial void DeletetblDonHang(tblDonHang instance);
    partial void InserttblGioHang(tblGioHang instance);
    partial void UpdatetblGioHang(tblGioHang instance);
    partial void DeletetblGioHang(tblGioHang instance);
    partial void InserttblMenu(tblMenu instance);
    partial void UpdatetblMenu(tblMenu instance);
    partial void DeletetblMenu(tblMenu instance);
    partial void InserttblSanPham(tblSanPham instance);
    partial void UpdatetblSanPham(tblSanPham instance);
    partial void DeletetblSanPham(tblSanPham instance);
    partial void InserttblSlider(tblSlider instance);
    partial void UpdatetblSlider(tblSlider instance);
    partial void DeletetblSlider(tblSlider instance);
    partial void InserttblThuongHieu(tblThuongHieu instance);
    partial void UpdatetblThuongHieu(tblThuongHieu instance);
    partial void DeletetblThuongHieu(tblThuongHieu instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dbWebsiteThuCungConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblAdmin> tblAdmins
		{
			get
			{
				return this.GetTable<tblAdmin>();
			}
		}
		
		public System.Data.Linq.Table<tblUser> tblUsers
		{
			get
			{
				return this.GetTable<tblUser>();
			}
		}
		
		public System.Data.Linq.Table<tblBaiViet> tblBaiViets
		{
			get
			{
				return this.GetTable<tblBaiViet>();
			}
		}
		
		public System.Data.Linq.Table<tblChiTietDonHang> tblChiTietDonHangs
		{
			get
			{
				return this.GetTable<tblChiTietDonHang>();
			}
		}
		
		public System.Data.Linq.Table<tblDanhMuc> tblDanhMucs
		{
			get
			{
				return this.GetTable<tblDanhMuc>();
			}
		}
		
		public System.Data.Linq.Table<tblDanhMucBaiViet> tblDanhMucBaiViets
		{
			get
			{
				return this.GetTable<tblDanhMucBaiViet>();
			}
		}
		
		public System.Data.Linq.Table<tblDanhMucCha> tblDanhMucChas
		{
			get
			{
				return this.GetTable<tblDanhMucCha>();
			}
		}
		
		public System.Data.Linq.Table<tblDonHang> tblDonHangs
		{
			get
			{
				return this.GetTable<tblDonHang>();
			}
		}
		
		public System.Data.Linq.Table<tblGioHang> tblGioHangs
		{
			get
			{
				return this.GetTable<tblGioHang>();
			}
		}
		
		public System.Data.Linq.Table<tblMenu> tblMenus
		{
			get
			{
				return this.GetTable<tblMenu>();
			}
		}
		
		public System.Data.Linq.Table<tblSanPham> tblSanPhams
		{
			get
			{
				return this.GetTable<tblSanPham>();
			}
		}
		
		public System.Data.Linq.Table<tblSlider> tblSliders
		{
			get
			{
				return this.GetTable<tblSlider>();
			}
		}
		
		public System.Data.Linq.Table<tblThuongHieu> tblThuongHieus
		{
			get
			{
				return this.GetTable<tblThuongHieu>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAdmin")]
	public partial class tblAdmin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_admin;
		
		private string _ho_ten;
		
		private string _sdt;
		
		private string _username;
		
		private string _pw;
		
		private byte _trang_thai;
		
		private System.DateTime _ngay_tao;
		
		private System.Nullable<System.DateTime> _ngay_cap_nhat;
		
		private EntitySet<tblBaiViet> _tblBaiViets;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_adminChanging(int value);
    partial void Onid_adminChanged();
    partial void Onho_tenChanging(string value);
    partial void Onho_tenChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpwChanging(string value);
    partial void OnpwChanged();
    partial void Ontrang_thaiChanging(byte value);
    partial void Ontrang_thaiChanged();
    partial void Onngay_taoChanging(System.DateTime value);
    partial void Onngay_taoChanged();
    partial void Onngay_cap_nhatChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_cap_nhatChanged();
    #endregion
		
		public tblAdmin()
		{
			this._tblBaiViets = new EntitySet<tblBaiViet>(new Action<tblBaiViet>(this.attach_tblBaiViets), new Action<tblBaiViet>(this.detach_tblBaiViets));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_admin", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_admin
		{
			get
			{
				return this._id_admin;
			}
			set
			{
				if ((this._id_admin != value))
				{
					this.Onid_adminChanging(value);
					this.SendPropertyChanging();
					this._id_admin = value;
					this.SendPropertyChanged("id_admin");
					this.Onid_adminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ho_ten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ho_ten
		{
			get
			{
				return this._ho_ten;
			}
			set
			{
				if ((this._ho_ten != value))
				{
					this.Onho_tenChanging(value);
					this.SendPropertyChanging();
					this._ho_ten = value;
					this.SendPropertyChanged("ho_ten");
					this.Onho_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pw", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pw
		{
			get
			{
				return this._pw;
			}
			set
			{
				if ((this._pw != value))
				{
					this.OnpwChanging(value);
					this.SendPropertyChanging();
					this._pw = value;
					this.SendPropertyChanged("pw");
					this.OnpwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="TinyInt NOT NULL")]
		public byte trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_cap_nhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_cap_nhat
		{
			get
			{
				return this._ngay_cap_nhat;
			}
			set
			{
				if ((this._ngay_cap_nhat != value))
				{
					this.Onngay_cap_nhatChanging(value);
					this.SendPropertyChanging();
					this._ngay_cap_nhat = value;
					this.SendPropertyChanged("ngay_cap_nhat");
					this.Onngay_cap_nhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblAdmin_tblBaiViet", Storage="_tblBaiViets", ThisKey="id_admin", OtherKey="id_admin")]
		public EntitySet<tblBaiViet> tblBaiViets
		{
			get
			{
				return this._tblBaiViets;
			}
			set
			{
				this._tblBaiViets.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblBaiViets(tblBaiViet entity)
		{
			this.SendPropertyChanging();
			entity.tblAdmin = this;
		}
		
		private void detach_tblBaiViets(tblBaiViet entity)
		{
			this.SendPropertyChanging();
			entity.tblAdmin = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUser")]
	public partial class tblUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_user;
		
		private string _email;
		
		private string _pw;
		
		private string _ho_ten;
		
		private string _sdt;
		
		private System.Nullable<System.DateTime> _ngay_sinh;
		
		private string _dia_chi;
		
		private byte _trang_thai;
		
		private System.DateTime _ngay_tao;
		
		private System.Nullable<System.DateTime> _ngay_cap_nhat;
		
		private EntitySet<tblDonHang> _tblDonHangs;
		
		private EntitySet<tblGioHang> _tblGioHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_userChanging(int value);
    partial void Onid_userChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnpwChanging(string value);
    partial void OnpwChanged();
    partial void Onho_tenChanging(string value);
    partial void Onho_tenChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void Onngay_sinhChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_sinhChanged();
    partial void Ondia_chiChanging(string value);
    partial void Ondia_chiChanged();
    partial void Ontrang_thaiChanging(byte value);
    partial void Ontrang_thaiChanged();
    partial void Onngay_taoChanging(System.DateTime value);
    partial void Onngay_taoChanged();
    partial void Onngay_cap_nhatChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_cap_nhatChanged();
    #endregion
		
		public tblUser()
		{
			this._tblDonHangs = new EntitySet<tblDonHang>(new Action<tblDonHang>(this.attach_tblDonHangs), new Action<tblDonHang>(this.detach_tblDonHangs));
			this._tblGioHangs = new EntitySet<tblGioHang>(new Action<tblGioHang>(this.attach_tblGioHangs), new Action<tblGioHang>(this.detach_tblGioHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_user", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_user
		{
			get
			{
				return this._id_user;
			}
			set
			{
				if ((this._id_user != value))
				{
					this.Onid_userChanging(value);
					this.SendPropertyChanging();
					this._id_user = value;
					this.SendPropertyChanged("id_user");
					this.Onid_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pw", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pw
		{
			get
			{
				return this._pw;
			}
			set
			{
				if ((this._pw != value))
				{
					this.OnpwChanging(value);
					this.SendPropertyChanging();
					this._pw = value;
					this.SendPropertyChanged("pw");
					this.OnpwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ho_ten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ho_ten
		{
			get
			{
				return this._ho_ten;
			}
			set
			{
				if ((this._ho_ten != value))
				{
					this.Onho_tenChanging(value);
					this.SendPropertyChanging();
					this._ho_ten = value;
					this.SendPropertyChanged("ho_ten");
					this.Onho_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_sinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_sinh
		{
			get
			{
				return this._ngay_sinh;
			}
			set
			{
				if ((this._ngay_sinh != value))
				{
					this.Onngay_sinhChanging(value);
					this.SendPropertyChanging();
					this._ngay_sinh = value;
					this.SendPropertyChanged("ngay_sinh");
					this.Onngay_sinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi", DbType="NVarChar(255)")]
		public string dia_chi
		{
			get
			{
				return this._dia_chi;
			}
			set
			{
				if ((this._dia_chi != value))
				{
					this.Ondia_chiChanging(value);
					this.SendPropertyChanging();
					this._dia_chi = value;
					this.SendPropertyChanged("dia_chi");
					this.Ondia_chiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="TinyInt NOT NULL")]
		public byte trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_cap_nhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_cap_nhat
		{
			get
			{
				return this._ngay_cap_nhat;
			}
			set
			{
				if ((this._ngay_cap_nhat != value))
				{
					this.Onngay_cap_nhatChanging(value);
					this.SendPropertyChanging();
					this._ngay_cap_nhat = value;
					this.SendPropertyChanged("ngay_cap_nhat");
					this.Onngay_cap_nhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUser_tblDonHang", Storage="_tblDonHangs", ThisKey="id_user", OtherKey="id_user")]
		public EntitySet<tblDonHang> tblDonHangs
		{
			get
			{
				return this._tblDonHangs;
			}
			set
			{
				this._tblDonHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUser_tblGioHang", Storage="_tblGioHangs", ThisKey="id_user", OtherKey="id_user")]
		public EntitySet<tblGioHang> tblGioHangs
		{
			get
			{
				return this._tblGioHangs;
			}
			set
			{
				this._tblGioHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblDonHangs(tblDonHang entity)
		{
			this.SendPropertyChanging();
			entity.tblUser = this;
		}
		
		private void detach_tblDonHangs(tblDonHang entity)
		{
			this.SendPropertyChanging();
			entity.tblUser = null;
		}
		
		private void attach_tblGioHangs(tblGioHang entity)
		{
			this.SendPropertyChanging();
			entity.tblUser = this;
		}
		
		private void detach_tblGioHangs(tblGioHang entity)
		{
			this.SendPropertyChanging();
			entity.tblUser = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblBaiViet")]
	public partial class tblBaiViet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_baiviet;
		
		private int _id_dmbaiviet;
		
		private int _id_admin;
		
		private string _tieu_de;
		
		private string _chi_tiet;
		
		private byte _trang_thai;
		
		private System.DateTime _ngay_tao;
		
		private System.Nullable<System.DateTime> _ngay_cap_nhat;
		
		private EntityRef<tblAdmin> _tblAdmin;
		
		private EntityRef<tblDanhMucBaiViet> _tblDanhMucBaiViet;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_baivietChanging(int value);
    partial void Onid_baivietChanged();
    partial void Onid_dmbaivietChanging(int value);
    partial void Onid_dmbaivietChanged();
    partial void Onid_adminChanging(int value);
    partial void Onid_adminChanged();
    partial void Ontieu_deChanging(string value);
    partial void Ontieu_deChanged();
    partial void Onchi_tietChanging(string value);
    partial void Onchi_tietChanged();
    partial void Ontrang_thaiChanging(byte value);
    partial void Ontrang_thaiChanged();
    partial void Onngay_taoChanging(System.DateTime value);
    partial void Onngay_taoChanged();
    partial void Onngay_cap_nhatChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_cap_nhatChanged();
    #endregion
		
		public tblBaiViet()
		{
			this._tblAdmin = default(EntityRef<tblAdmin>);
			this._tblDanhMucBaiViet = default(EntityRef<tblDanhMucBaiViet>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_baiviet", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_baiviet
		{
			get
			{
				return this._id_baiviet;
			}
			set
			{
				if ((this._id_baiviet != value))
				{
					this.Onid_baivietChanging(value);
					this.SendPropertyChanging();
					this._id_baiviet = value;
					this.SendPropertyChanged("id_baiviet");
					this.Onid_baivietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dmbaiviet", DbType="Int NOT NULL")]
		public int id_dmbaiviet
		{
			get
			{
				return this._id_dmbaiviet;
			}
			set
			{
				if ((this._id_dmbaiviet != value))
				{
					if (this._tblDanhMucBaiViet.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_dmbaivietChanging(value);
					this.SendPropertyChanging();
					this._id_dmbaiviet = value;
					this.SendPropertyChanged("id_dmbaiviet");
					this.Onid_dmbaivietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_admin", DbType="Int NOT NULL")]
		public int id_admin
		{
			get
			{
				return this._id_admin;
			}
			set
			{
				if ((this._id_admin != value))
				{
					if (this._tblAdmin.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_adminChanging(value);
					this.SendPropertyChanging();
					this._id_admin = value;
					this.SendPropertyChanged("id_admin");
					this.Onid_adminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tieu_de", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string tieu_de
		{
			get
			{
				return this._tieu_de;
			}
			set
			{
				if ((this._tieu_de != value))
				{
					this.Ontieu_deChanging(value);
					this.SendPropertyChanging();
					this._tieu_de = value;
					this.SendPropertyChanged("tieu_de");
					this.Ontieu_deChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chi_tiet", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string chi_tiet
		{
			get
			{
				return this._chi_tiet;
			}
			set
			{
				if ((this._chi_tiet != value))
				{
					this.Onchi_tietChanging(value);
					this.SendPropertyChanging();
					this._chi_tiet = value;
					this.SendPropertyChanged("chi_tiet");
					this.Onchi_tietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="TinyInt NOT NULL")]
		public byte trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_cap_nhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_cap_nhat
		{
			get
			{
				return this._ngay_cap_nhat;
			}
			set
			{
				if ((this._ngay_cap_nhat != value))
				{
					this.Onngay_cap_nhatChanging(value);
					this.SendPropertyChanging();
					this._ngay_cap_nhat = value;
					this.SendPropertyChanged("ngay_cap_nhat");
					this.Onngay_cap_nhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblAdmin_tblBaiViet", Storage="_tblAdmin", ThisKey="id_admin", OtherKey="id_admin", IsForeignKey=true)]
		public tblAdmin tblAdmin
		{
			get
			{
				return this._tblAdmin.Entity;
			}
			set
			{
				tblAdmin previousValue = this._tblAdmin.Entity;
				if (((previousValue != value) 
							|| (this._tblAdmin.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblAdmin.Entity = null;
						previousValue.tblBaiViets.Remove(this);
					}
					this._tblAdmin.Entity = value;
					if ((value != null))
					{
						value.tblBaiViets.Add(this);
						this._id_admin = value.id_admin;
					}
					else
					{
						this._id_admin = default(int);
					}
					this.SendPropertyChanged("tblAdmin");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDanhMucBaiViet_tblBaiViet", Storage="_tblDanhMucBaiViet", ThisKey="id_dmbaiviet", OtherKey="id_dmbaiviet", IsForeignKey=true)]
		public tblDanhMucBaiViet tblDanhMucBaiViet
		{
			get
			{
				return this._tblDanhMucBaiViet.Entity;
			}
			set
			{
				tblDanhMucBaiViet previousValue = this._tblDanhMucBaiViet.Entity;
				if (((previousValue != value) 
							|| (this._tblDanhMucBaiViet.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblDanhMucBaiViet.Entity = null;
						previousValue.tblBaiViets.Remove(this);
					}
					this._tblDanhMucBaiViet.Entity = value;
					if ((value != null))
					{
						value.tblBaiViets.Add(this);
						this._id_dmbaiviet = value.id_dmbaiviet;
					}
					else
					{
						this._id_dmbaiviet = default(int);
					}
					this.SendPropertyChanged("tblDanhMucBaiViet");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblChiTietDonHang")]
	public partial class tblChiTietDonHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_chitietdonhang;
		
		private int _id_sanpham;
		
		private int _id_donhang;
		
		private int _so_luong;
		
		private decimal _gia_ban;
		
		private EntityRef<tblDonHang> _tblDonHang;
		
		private EntityRef<tblSanPham> _tblSanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_chitietdonhangChanging(int value);
    partial void Onid_chitietdonhangChanged();
    partial void Onid_sanphamChanging(int value);
    partial void Onid_sanphamChanged();
    partial void Onid_donhangChanging(int value);
    partial void Onid_donhangChanged();
    partial void Onso_luongChanging(int value);
    partial void Onso_luongChanged();
    partial void Ongia_banChanging(decimal value);
    partial void Ongia_banChanged();
    #endregion
		
		public tblChiTietDonHang()
		{
			this._tblDonHang = default(EntityRef<tblDonHang>);
			this._tblSanPham = default(EntityRef<tblSanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_chitietdonhang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_chitietdonhang
		{
			get
			{
				return this._id_chitietdonhang;
			}
			set
			{
				if ((this._id_chitietdonhang != value))
				{
					this.Onid_chitietdonhangChanging(value);
					this.SendPropertyChanging();
					this._id_chitietdonhang = value;
					this.SendPropertyChanged("id_chitietdonhang");
					this.Onid_chitietdonhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sanpham", DbType="Int NOT NULL")]
		public int id_sanpham
		{
			get
			{
				return this._id_sanpham;
			}
			set
			{
				if ((this._id_sanpham != value))
				{
					if (this._tblSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_sanphamChanging(value);
					this.SendPropertyChanging();
					this._id_sanpham = value;
					this.SendPropertyChanged("id_sanpham");
					this.Onid_sanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_donhang", DbType="Int NOT NULL")]
		public int id_donhang
		{
			get
			{
				return this._id_donhang;
			}
			set
			{
				if ((this._id_donhang != value))
				{
					if (this._tblDonHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_donhangChanging(value);
					this.SendPropertyChanging();
					this._id_donhang = value;
					this.SendPropertyChanged("id_donhang");
					this.Onid_donhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong", DbType="Int NOT NULL")]
		public int so_luong
		{
			get
			{
				return this._so_luong;
			}
			set
			{
				if ((this._so_luong != value))
				{
					this.Onso_luongChanging(value);
					this.SendPropertyChanging();
					this._so_luong = value;
					this.SendPropertyChanged("so_luong");
					this.Onso_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia_ban", DbType="Decimal(18,0) NOT NULL")]
		public decimal gia_ban
		{
			get
			{
				return this._gia_ban;
			}
			set
			{
				if ((this._gia_ban != value))
				{
					this.Ongia_banChanging(value);
					this.SendPropertyChanging();
					this._gia_ban = value;
					this.SendPropertyChanged("gia_ban");
					this.Ongia_banChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDonHang_tblChiTietDonHang", Storage="_tblDonHang", ThisKey="id_donhang", OtherKey="id_donhang", IsForeignKey=true)]
		public tblDonHang tblDonHang
		{
			get
			{
				return this._tblDonHang.Entity;
			}
			set
			{
				tblDonHang previousValue = this._tblDonHang.Entity;
				if (((previousValue != value) 
							|| (this._tblDonHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblDonHang.Entity = null;
						previousValue.tblChiTietDonHangs.Remove(this);
					}
					this._tblDonHang.Entity = value;
					if ((value != null))
					{
						value.tblChiTietDonHangs.Add(this);
						this._id_donhang = value.id_donhang;
					}
					else
					{
						this._id_donhang = default(int);
					}
					this.SendPropertyChanged("tblDonHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSanPham_tblChiTietDonHang", Storage="_tblSanPham", ThisKey="id_sanpham", OtherKey="id_sanpham", IsForeignKey=true)]
		public tblSanPham tblSanPham
		{
			get
			{
				return this._tblSanPham.Entity;
			}
			set
			{
				tblSanPham previousValue = this._tblSanPham.Entity;
				if (((previousValue != value) 
							|| (this._tblSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblSanPham.Entity = null;
						previousValue.tblChiTietDonHangs.Remove(this);
					}
					this._tblSanPham.Entity = value;
					if ((value != null))
					{
						value.tblChiTietDonHangs.Add(this);
						this._id_sanpham = value.id_sanpham;
					}
					else
					{
						this._id_sanpham = default(int);
					}
					this.SendPropertyChanged("tblSanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDanhMuc")]
	public partial class tblDanhMuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_danhmuc;
		
		private int _id_danhmuc_cha;
		
		private string _ten_danhmuc;
		
		private string _meta_name;
		
		private System.DateTime _ngay_tao;
		
		private byte _trang_thai;
		
		private EntitySet<tblSanPham> _tblSanPhams;
		
		private EntityRef<tblDanhMucCha> _tblDanhMucCha;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_danhmucChanging(int value);
    partial void Onid_danhmucChanged();
    partial void Onid_danhmuc_chaChanging(int value);
    partial void Onid_danhmuc_chaChanged();
    partial void Onten_danhmucChanging(string value);
    partial void Onten_danhmucChanged();
    partial void Onmeta_nameChanging(string value);
    partial void Onmeta_nameChanged();
    partial void Onngay_taoChanging(System.DateTime value);
    partial void Onngay_taoChanged();
    partial void Ontrang_thaiChanging(byte value);
    partial void Ontrang_thaiChanged();
    #endregion
		
		public tblDanhMuc()
		{
			this._tblSanPhams = new EntitySet<tblSanPham>(new Action<tblSanPham>(this.attach_tblSanPhams), new Action<tblSanPham>(this.detach_tblSanPhams));
			this._tblDanhMucCha = default(EntityRef<tblDanhMucCha>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_danhmuc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_danhmuc
		{
			get
			{
				return this._id_danhmuc;
			}
			set
			{
				if ((this._id_danhmuc != value))
				{
					this.Onid_danhmucChanging(value);
					this.SendPropertyChanging();
					this._id_danhmuc = value;
					this.SendPropertyChanged("id_danhmuc");
					this.Onid_danhmucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_danhmuc_cha", DbType="Int NOT NULL")]
		public int id_danhmuc_cha
		{
			get
			{
				return this._id_danhmuc_cha;
			}
			set
			{
				if ((this._id_danhmuc_cha != value))
				{
					if (this._tblDanhMucCha.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_danhmuc_chaChanging(value);
					this.SendPropertyChanging();
					this._id_danhmuc_cha = value;
					this.SendPropertyChanged("id_danhmuc_cha");
					this.Onid_danhmuc_chaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_danhmuc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ten_danhmuc
		{
			get
			{
				return this._ten_danhmuc;
			}
			set
			{
				if ((this._ten_danhmuc != value))
				{
					this.Onten_danhmucChanging(value);
					this.SendPropertyChanging();
					this._ten_danhmuc = value;
					this.SendPropertyChanged("ten_danhmuc");
					this.Onten_danhmucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_meta_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string meta_name
		{
			get
			{
				return this._meta_name;
			}
			set
			{
				if ((this._meta_name != value))
				{
					this.Onmeta_nameChanging(value);
					this.SendPropertyChanging();
					this._meta_name = value;
					this.SendPropertyChanged("meta_name");
					this.Onmeta_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="TinyInt NOT NULL")]
		public byte trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDanhMuc_tblSanPham", Storage="_tblSanPhams", ThisKey="id_danhmuc", OtherKey="id_danhmuc")]
		public EntitySet<tblSanPham> tblSanPhams
		{
			get
			{
				return this._tblSanPhams;
			}
			set
			{
				this._tblSanPhams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDanhMucCha_tblDanhMuc", Storage="_tblDanhMucCha", ThisKey="id_danhmuc_cha", OtherKey="id_danhmuc_cha", IsForeignKey=true)]
		public tblDanhMucCha tblDanhMucCha
		{
			get
			{
				return this._tblDanhMucCha.Entity;
			}
			set
			{
				tblDanhMucCha previousValue = this._tblDanhMucCha.Entity;
				if (((previousValue != value) 
							|| (this._tblDanhMucCha.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblDanhMucCha.Entity = null;
						previousValue.tblDanhMucs.Remove(this);
					}
					this._tblDanhMucCha.Entity = value;
					if ((value != null))
					{
						value.tblDanhMucs.Add(this);
						this._id_danhmuc_cha = value.id_danhmuc_cha;
					}
					else
					{
						this._id_danhmuc_cha = default(int);
					}
					this.SendPropertyChanged("tblDanhMucCha");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblSanPhams(tblSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tblDanhMuc = this;
		}
		
		private void detach_tblSanPhams(tblSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tblDanhMuc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDanhMucBaiViet")]
	public partial class tblDanhMucBaiViet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_dmbaiviet;
		
		private string _ten_dmbaiviet;
		
		private string _meta_name;
		
		private byte _trang_thai;
		
		private System.DateTime _ngay_tao;
		
		private System.Nullable<System.DateTime> _ngay_cap_nhat;
		
		private EntitySet<tblBaiViet> _tblBaiViets;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_dmbaivietChanging(int value);
    partial void Onid_dmbaivietChanged();
    partial void Onten_dmbaivietChanging(string value);
    partial void Onten_dmbaivietChanged();
    partial void Onmeta_nameChanging(string value);
    partial void Onmeta_nameChanged();
    partial void Ontrang_thaiChanging(byte value);
    partial void Ontrang_thaiChanged();
    partial void Onngay_taoChanging(System.DateTime value);
    partial void Onngay_taoChanged();
    partial void Onngay_cap_nhatChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_cap_nhatChanged();
    #endregion
		
		public tblDanhMucBaiViet()
		{
			this._tblBaiViets = new EntitySet<tblBaiViet>(new Action<tblBaiViet>(this.attach_tblBaiViets), new Action<tblBaiViet>(this.detach_tblBaiViets));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dmbaiviet", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_dmbaiviet
		{
			get
			{
				return this._id_dmbaiviet;
			}
			set
			{
				if ((this._id_dmbaiviet != value))
				{
					this.Onid_dmbaivietChanging(value);
					this.SendPropertyChanging();
					this._id_dmbaiviet = value;
					this.SendPropertyChanged("id_dmbaiviet");
					this.Onid_dmbaivietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_dmbaiviet", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ten_dmbaiviet
		{
			get
			{
				return this._ten_dmbaiviet;
			}
			set
			{
				if ((this._ten_dmbaiviet != value))
				{
					this.Onten_dmbaivietChanging(value);
					this.SendPropertyChanging();
					this._ten_dmbaiviet = value;
					this.SendPropertyChanged("ten_dmbaiviet");
					this.Onten_dmbaivietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_meta_name", DbType="VarChar(50)")]
		public string meta_name
		{
			get
			{
				return this._meta_name;
			}
			set
			{
				if ((this._meta_name != value))
				{
					this.Onmeta_nameChanging(value);
					this.SendPropertyChanging();
					this._meta_name = value;
					this.SendPropertyChanged("meta_name");
					this.Onmeta_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="TinyInt NOT NULL")]
		public byte trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_cap_nhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_cap_nhat
		{
			get
			{
				return this._ngay_cap_nhat;
			}
			set
			{
				if ((this._ngay_cap_nhat != value))
				{
					this.Onngay_cap_nhatChanging(value);
					this.SendPropertyChanging();
					this._ngay_cap_nhat = value;
					this.SendPropertyChanged("ngay_cap_nhat");
					this.Onngay_cap_nhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDanhMucBaiViet_tblBaiViet", Storage="_tblBaiViets", ThisKey="id_dmbaiviet", OtherKey="id_dmbaiviet")]
		public EntitySet<tblBaiViet> tblBaiViets
		{
			get
			{
				return this._tblBaiViets;
			}
			set
			{
				this._tblBaiViets.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblBaiViets(tblBaiViet entity)
		{
			this.SendPropertyChanging();
			entity.tblDanhMucBaiViet = this;
		}
		
		private void detach_tblBaiViets(tblBaiViet entity)
		{
			this.SendPropertyChanging();
			entity.tblDanhMucBaiViet = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDanhMucCha")]
	public partial class tblDanhMucCha : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_danhmuc_cha;
		
		private string _ten_danhmuc_cha;
		
		private string _meta_name;
		
		private System.DateTime _ngay_tao;
		
		private byte _trang_thai;
		
		private EntitySet<tblDanhMuc> _tblDanhMucs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_danhmuc_chaChanging(int value);
    partial void Onid_danhmuc_chaChanged();
    partial void Onten_danhmuc_chaChanging(string value);
    partial void Onten_danhmuc_chaChanged();
    partial void Onmeta_nameChanging(string value);
    partial void Onmeta_nameChanged();
    partial void Onngay_taoChanging(System.DateTime value);
    partial void Onngay_taoChanged();
    partial void Ontrang_thaiChanging(byte value);
    partial void Ontrang_thaiChanged();
    #endregion
		
		public tblDanhMucCha()
		{
			this._tblDanhMucs = new EntitySet<tblDanhMuc>(new Action<tblDanhMuc>(this.attach_tblDanhMucs), new Action<tblDanhMuc>(this.detach_tblDanhMucs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_danhmuc_cha", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_danhmuc_cha
		{
			get
			{
				return this._id_danhmuc_cha;
			}
			set
			{
				if ((this._id_danhmuc_cha != value))
				{
					this.Onid_danhmuc_chaChanging(value);
					this.SendPropertyChanging();
					this._id_danhmuc_cha = value;
					this.SendPropertyChanged("id_danhmuc_cha");
					this.Onid_danhmuc_chaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_danhmuc_cha", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ten_danhmuc_cha
		{
			get
			{
				return this._ten_danhmuc_cha;
			}
			set
			{
				if ((this._ten_danhmuc_cha != value))
				{
					this.Onten_danhmuc_chaChanging(value);
					this.SendPropertyChanging();
					this._ten_danhmuc_cha = value;
					this.SendPropertyChanged("ten_danhmuc_cha");
					this.Onten_danhmuc_chaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_meta_name", DbType="VarChar(50)")]
		public string meta_name
		{
			get
			{
				return this._meta_name;
			}
			set
			{
				if ((this._meta_name != value))
				{
					this.Onmeta_nameChanging(value);
					this.SendPropertyChanging();
					this._meta_name = value;
					this.SendPropertyChanged("meta_name");
					this.Onmeta_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="TinyInt NOT NULL")]
		public byte trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDanhMucCha_tblDanhMuc", Storage="_tblDanhMucs", ThisKey="id_danhmuc_cha", OtherKey="id_danhmuc_cha")]
		public EntitySet<tblDanhMuc> tblDanhMucs
		{
			get
			{
				return this._tblDanhMucs;
			}
			set
			{
				this._tblDanhMucs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblDanhMucs(tblDanhMuc entity)
		{
			this.SendPropertyChanging();
			entity.tblDanhMucCha = this;
		}
		
		private void detach_tblDanhMucs(tblDanhMuc entity)
		{
			this.SendPropertyChanging();
			entity.tblDanhMucCha = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDonHang")]
	public partial class tblDonHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_donhang;
		
		private int _id_user;
		
		private string _ho_ten;
		
		private string _email;
		
		private string _sdt;
		
		private string _noi_nhan;
		
		private int _so_luong;
		
		private decimal _tong_tien;
		
		private string _ghi_chu;
		
		private string _hinh_thuc_thanh_toan;
		
		private byte _trang_thai;
		
		private System.DateTime _ngay_tao;
		
		private EntitySet<tblChiTietDonHang> _tblChiTietDonHangs;
		
		private EntityRef<tblUser> _tblUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_donhangChanging(int value);
    partial void Onid_donhangChanged();
    partial void Onid_userChanging(int value);
    partial void Onid_userChanged();
    partial void Onho_tenChanging(string value);
    partial void Onho_tenChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void Onnoi_nhanChanging(string value);
    partial void Onnoi_nhanChanged();
    partial void Onso_luongChanging(int value);
    partial void Onso_luongChanged();
    partial void Ontong_tienChanging(decimal value);
    partial void Ontong_tienChanged();
    partial void Onghi_chuChanging(string value);
    partial void Onghi_chuChanged();
    partial void Onhinh_thuc_thanh_toanChanging(string value);
    partial void Onhinh_thuc_thanh_toanChanged();
    partial void Ontrang_thaiChanging(byte value);
    partial void Ontrang_thaiChanged();
    partial void Onngay_taoChanging(System.DateTime value);
    partial void Onngay_taoChanged();
    #endregion
		
		public tblDonHang()
		{
			this._tblChiTietDonHangs = new EntitySet<tblChiTietDonHang>(new Action<tblChiTietDonHang>(this.attach_tblChiTietDonHangs), new Action<tblChiTietDonHang>(this.detach_tblChiTietDonHangs));
			this._tblUser = default(EntityRef<tblUser>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_donhang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_donhang
		{
			get
			{
				return this._id_donhang;
			}
			set
			{
				if ((this._id_donhang != value))
				{
					this.Onid_donhangChanging(value);
					this.SendPropertyChanging();
					this._id_donhang = value;
					this.SendPropertyChanged("id_donhang");
					this.Onid_donhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_user", DbType="Int NOT NULL")]
		public int id_user
		{
			get
			{
				return this._id_user;
			}
			set
			{
				if ((this._id_user != value))
				{
					if (this._tblUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_userChanging(value);
					this.SendPropertyChanging();
					this._id_user = value;
					this.SendPropertyChanged("id_user");
					this.Onid_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ho_ten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ho_ten
		{
			get
			{
				return this._ho_ten;
			}
			set
			{
				if ((this._ho_ten != value))
				{
					this.Onho_tenChanging(value);
					this.SendPropertyChanging();
					this._ho_ten = value;
					this.SendPropertyChanged("ho_ten");
					this.Onho_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noi_nhan", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string noi_nhan
		{
			get
			{
				return this._noi_nhan;
			}
			set
			{
				if ((this._noi_nhan != value))
				{
					this.Onnoi_nhanChanging(value);
					this.SendPropertyChanging();
					this._noi_nhan = value;
					this.SendPropertyChanged("noi_nhan");
					this.Onnoi_nhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong", DbType="Int NOT NULL")]
		public int so_luong
		{
			get
			{
				return this._so_luong;
			}
			set
			{
				if ((this._so_luong != value))
				{
					this.Onso_luongChanging(value);
					this.SendPropertyChanging();
					this._so_luong = value;
					this.SendPropertyChanged("so_luong");
					this.Onso_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tong_tien", DbType="Decimal(18,0) NOT NULL")]
		public decimal tong_tien
		{
			get
			{
				return this._tong_tien;
			}
			set
			{
				if ((this._tong_tien != value))
				{
					this.Ontong_tienChanging(value);
					this.SendPropertyChanging();
					this._tong_tien = value;
					this.SendPropertyChanged("tong_tien");
					this.Ontong_tienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghi_chu", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string ghi_chu
		{
			get
			{
				return this._ghi_chu;
			}
			set
			{
				if ((this._ghi_chu != value))
				{
					this.Onghi_chuChanging(value);
					this.SendPropertyChanging();
					this._ghi_chu = value;
					this.SendPropertyChanged("ghi_chu");
					this.Onghi_chuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh_thuc_thanh_toan", DbType="VarChar(100)")]
		public string hinh_thuc_thanh_toan
		{
			get
			{
				return this._hinh_thuc_thanh_toan;
			}
			set
			{
				if ((this._hinh_thuc_thanh_toan != value))
				{
					this.Onhinh_thuc_thanh_toanChanging(value);
					this.SendPropertyChanging();
					this._hinh_thuc_thanh_toan = value;
					this.SendPropertyChanged("hinh_thuc_thanh_toan");
					this.Onhinh_thuc_thanh_toanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="TinyInt NOT NULL")]
		public byte trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDonHang_tblChiTietDonHang", Storage="_tblChiTietDonHangs", ThisKey="id_donhang", OtherKey="id_donhang")]
		public EntitySet<tblChiTietDonHang> tblChiTietDonHangs
		{
			get
			{
				return this._tblChiTietDonHangs;
			}
			set
			{
				this._tblChiTietDonHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUser_tblDonHang", Storage="_tblUser", ThisKey="id_user", OtherKey="id_user", IsForeignKey=true)]
		public tblUser tblUser
		{
			get
			{
				return this._tblUser.Entity;
			}
			set
			{
				tblUser previousValue = this._tblUser.Entity;
				if (((previousValue != value) 
							|| (this._tblUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUser.Entity = null;
						previousValue.tblDonHangs.Remove(this);
					}
					this._tblUser.Entity = value;
					if ((value != null))
					{
						value.tblDonHangs.Add(this);
						this._id_user = value.id_user;
					}
					else
					{
						this._id_user = default(int);
					}
					this.SendPropertyChanged("tblUser");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblChiTietDonHangs(tblChiTietDonHang entity)
		{
			this.SendPropertyChanging();
			entity.tblDonHang = this;
		}
		
		private void detach_tblChiTietDonHangs(tblChiTietDonHang entity)
		{
			this.SendPropertyChanging();
			entity.tblDonHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblGioHang")]
	public partial class tblGioHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_giohang;
		
		private int _id_user;
		
		private int _id_sanpham;
		
		private int _so_luong;
		
		private System.DateTime _ngay_tao;
		
		private EntityRef<tblUser> _tblUser;
		
		private EntityRef<tblSanPham> _tblSanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_giohangChanging(int value);
    partial void Onid_giohangChanged();
    partial void Onid_userChanging(int value);
    partial void Onid_userChanged();
    partial void Onid_sanphamChanging(int value);
    partial void Onid_sanphamChanged();
    partial void Onso_luongChanging(int value);
    partial void Onso_luongChanged();
    partial void Onngay_taoChanging(System.DateTime value);
    partial void Onngay_taoChanged();
    #endregion
		
		public tblGioHang()
		{
			this._tblUser = default(EntityRef<tblUser>);
			this._tblSanPham = default(EntityRef<tblSanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_giohang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_giohang
		{
			get
			{
				return this._id_giohang;
			}
			set
			{
				if ((this._id_giohang != value))
				{
					this.Onid_giohangChanging(value);
					this.SendPropertyChanging();
					this._id_giohang = value;
					this.SendPropertyChanged("id_giohang");
					this.Onid_giohangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_user", DbType="Int NOT NULL")]
		public int id_user
		{
			get
			{
				return this._id_user;
			}
			set
			{
				if ((this._id_user != value))
				{
					if (this._tblUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_userChanging(value);
					this.SendPropertyChanging();
					this._id_user = value;
					this.SendPropertyChanged("id_user");
					this.Onid_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sanpham", DbType="Int NOT NULL")]
		public int id_sanpham
		{
			get
			{
				return this._id_sanpham;
			}
			set
			{
				if ((this._id_sanpham != value))
				{
					if (this._tblSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_sanphamChanging(value);
					this.SendPropertyChanging();
					this._id_sanpham = value;
					this.SendPropertyChanged("id_sanpham");
					this.Onid_sanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong", DbType="Int NOT NULL")]
		public int so_luong
		{
			get
			{
				return this._so_luong;
			}
			set
			{
				if ((this._so_luong != value))
				{
					this.Onso_luongChanging(value);
					this.SendPropertyChanging();
					this._so_luong = value;
					this.SendPropertyChanged("so_luong");
					this.Onso_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUser_tblGioHang", Storage="_tblUser", ThisKey="id_user", OtherKey="id_user", IsForeignKey=true)]
		public tblUser tblUser
		{
			get
			{
				return this._tblUser.Entity;
			}
			set
			{
				tblUser previousValue = this._tblUser.Entity;
				if (((previousValue != value) 
							|| (this._tblUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUser.Entity = null;
						previousValue.tblGioHangs.Remove(this);
					}
					this._tblUser.Entity = value;
					if ((value != null))
					{
						value.tblGioHangs.Add(this);
						this._id_user = value.id_user;
					}
					else
					{
						this._id_user = default(int);
					}
					this.SendPropertyChanged("tblUser");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSanPham_tblGioHang", Storage="_tblSanPham", ThisKey="id_sanpham", OtherKey="id_sanpham", IsForeignKey=true)]
		public tblSanPham tblSanPham
		{
			get
			{
				return this._tblSanPham.Entity;
			}
			set
			{
				tblSanPham previousValue = this._tblSanPham.Entity;
				if (((previousValue != value) 
							|| (this._tblSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblSanPham.Entity = null;
						previousValue.tblGioHangs.Remove(this);
					}
					this._tblSanPham.Entity = value;
					if ((value != null))
					{
						value.tblGioHangs.Add(this);
						this._id_sanpham = value.id_sanpham;
					}
					else
					{
						this._id_sanpham = default(int);
					}
					this.SendPropertyChanged("tblSanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMenu")]
	public partial class tblMenu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_menu;
		
		private string _ten_menu;
		
		private string _meta_name;
		
		private System.DateTime _ngay_tao;
		
		private System.Nullable<System.DateTime> _ngay_cap_nhat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_menuChanging(int value);
    partial void Onid_menuChanged();
    partial void Onten_menuChanging(string value);
    partial void Onten_menuChanged();
    partial void Onmeta_nameChanging(string value);
    partial void Onmeta_nameChanged();
    partial void Onngay_taoChanging(System.DateTime value);
    partial void Onngay_taoChanged();
    partial void Onngay_cap_nhatChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_cap_nhatChanged();
    #endregion
		
		public tblMenu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_menu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_menu
		{
			get
			{
				return this._id_menu;
			}
			set
			{
				if ((this._id_menu != value))
				{
					this.Onid_menuChanging(value);
					this.SendPropertyChanging();
					this._id_menu = value;
					this.SendPropertyChanged("id_menu");
					this.Onid_menuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_menu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ten_menu
		{
			get
			{
				return this._ten_menu;
			}
			set
			{
				if ((this._ten_menu != value))
				{
					this.Onten_menuChanging(value);
					this.SendPropertyChanging();
					this._ten_menu = value;
					this.SendPropertyChanged("ten_menu");
					this.Onten_menuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_meta_name", DbType="VarChar(50)")]
		public string meta_name
		{
			get
			{
				return this._meta_name;
			}
			set
			{
				if ((this._meta_name != value))
				{
					this.Onmeta_nameChanging(value);
					this.SendPropertyChanging();
					this._meta_name = value;
					this.SendPropertyChanged("meta_name");
					this.Onmeta_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_cap_nhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_cap_nhat
		{
			get
			{
				return this._ngay_cap_nhat;
			}
			set
			{
				if ((this._ngay_cap_nhat != value))
				{
					this.Onngay_cap_nhatChanging(value);
					this.SendPropertyChanging();
					this._ngay_cap_nhat = value;
					this.SendPropertyChanged("ngay_cap_nhat");
					this.Onngay_cap_nhatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSanPham")]
	public partial class tblSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_sanpham;
		
		private string _ten_sanpham;
		
		private string _meta_name;
		
		private int _id_danhmuc;
		
		private System.Nullable<int> _id_thuonghieu;
		
		private string _mo_ta;
		
		private string _cong_dung;
		
		private string _huong_dan_su_dung;
		
		private string _bao_quan;
		
		private decimal _gia_mua;
		
		private decimal _gia_ban;
		
		private decimal _gia_khuyen_mai;
		
		private int _so_luong;
		
		private string _hinhanh;
		
		private System.Nullable<byte> _sanphammoi;
		
		private System.Nullable<byte> _noibat;
		
		private byte _trangthai;
		
		private System.DateTime _ngay_tao;
		
		private System.Nullable<System.DateTime> _ngay_cap_nhap;
		
		private EntitySet<tblChiTietDonHang> _tblChiTietDonHangs;
		
		private EntitySet<tblGioHang> _tblGioHangs;
		
		private EntityRef<tblDanhMuc> _tblDanhMuc;
		
		private EntityRef<tblThuongHieu> _tblThuongHieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_sanphamChanging(int value);
    partial void Onid_sanphamChanged();
    partial void Onten_sanphamChanging(string value);
    partial void Onten_sanphamChanged();
    partial void Onmeta_nameChanging(string value);
    partial void Onmeta_nameChanged();
    partial void Onid_danhmucChanging(int value);
    partial void Onid_danhmucChanged();
    partial void Onid_thuonghieuChanging(System.Nullable<int> value);
    partial void Onid_thuonghieuChanged();
    partial void Onmo_taChanging(string value);
    partial void Onmo_taChanged();
    partial void Oncong_dungChanging(string value);
    partial void Oncong_dungChanged();
    partial void Onhuong_dan_su_dungChanging(string value);
    partial void Onhuong_dan_su_dungChanged();
    partial void Onbao_quanChanging(string value);
    partial void Onbao_quanChanged();
    partial void Ongia_muaChanging(decimal value);
    partial void Ongia_muaChanged();
    partial void Ongia_banChanging(decimal value);
    partial void Ongia_banChanged();
    partial void Ongia_khuyen_maiChanging(decimal value);
    partial void Ongia_khuyen_maiChanged();
    partial void Onso_luongChanging(int value);
    partial void Onso_luongChanged();
    partial void OnhinhanhChanging(string value);
    partial void OnhinhanhChanged();
    partial void OnsanphammoiChanging(System.Nullable<byte> value);
    partial void OnsanphammoiChanged();
    partial void OnnoibatChanging(System.Nullable<byte> value);
    partial void OnnoibatChanged();
    partial void OntrangthaiChanging(byte value);
    partial void OntrangthaiChanged();
    partial void Onngay_taoChanging(System.DateTime value);
    partial void Onngay_taoChanged();
    partial void Onngay_cap_nhapChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_cap_nhapChanged();
    #endregion
		
		public tblSanPham()
		{
			this._tblChiTietDonHangs = new EntitySet<tblChiTietDonHang>(new Action<tblChiTietDonHang>(this.attach_tblChiTietDonHangs), new Action<tblChiTietDonHang>(this.detach_tblChiTietDonHangs));
			this._tblGioHangs = new EntitySet<tblGioHang>(new Action<tblGioHang>(this.attach_tblGioHangs), new Action<tblGioHang>(this.detach_tblGioHangs));
			this._tblDanhMuc = default(EntityRef<tblDanhMuc>);
			this._tblThuongHieu = default(EntityRef<tblThuongHieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sanpham", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_sanpham
		{
			get
			{
				return this._id_sanpham;
			}
			set
			{
				if ((this._id_sanpham != value))
				{
					this.Onid_sanphamChanging(value);
					this.SendPropertyChanging();
					this._id_sanpham = value;
					this.SendPropertyChanged("id_sanpham");
					this.Onid_sanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_sanpham", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ten_sanpham
		{
			get
			{
				return this._ten_sanpham;
			}
			set
			{
				if ((this._ten_sanpham != value))
				{
					this.Onten_sanphamChanging(value);
					this.SendPropertyChanging();
					this._ten_sanpham = value;
					this.SendPropertyChanged("ten_sanpham");
					this.Onten_sanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_meta_name", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string meta_name
		{
			get
			{
				return this._meta_name;
			}
			set
			{
				if ((this._meta_name != value))
				{
					this.Onmeta_nameChanging(value);
					this.SendPropertyChanging();
					this._meta_name = value;
					this.SendPropertyChanged("meta_name");
					this.Onmeta_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_danhmuc", DbType="Int NOT NULL")]
		public int id_danhmuc
		{
			get
			{
				return this._id_danhmuc;
			}
			set
			{
				if ((this._id_danhmuc != value))
				{
					if (this._tblDanhMuc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_danhmucChanging(value);
					this.SendPropertyChanging();
					this._id_danhmuc = value;
					this.SendPropertyChanged("id_danhmuc");
					this.Onid_danhmucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_thuonghieu", DbType="Int")]
		public System.Nullable<int> id_thuonghieu
		{
			get
			{
				return this._id_thuonghieu;
			}
			set
			{
				if ((this._id_thuonghieu != value))
				{
					if (this._tblThuongHieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_thuonghieuChanging(value);
					this.SendPropertyChanging();
					this._id_thuonghieu = value;
					this.SendPropertyChanged("id_thuonghieu");
					this.Onid_thuonghieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_ta", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string mo_ta
		{
			get
			{
				return this._mo_ta;
			}
			set
			{
				if ((this._mo_ta != value))
				{
					this.Onmo_taChanging(value);
					this.SendPropertyChanging();
					this._mo_ta = value;
					this.SendPropertyChanged("mo_ta");
					this.Onmo_taChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cong_dung", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string cong_dung
		{
			get
			{
				return this._cong_dung;
			}
			set
			{
				if ((this._cong_dung != value))
				{
					this.Oncong_dungChanging(value);
					this.SendPropertyChanging();
					this._cong_dung = value;
					this.SendPropertyChanged("cong_dung");
					this.Oncong_dungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_huong_dan_su_dung", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string huong_dan_su_dung
		{
			get
			{
				return this._huong_dan_su_dung;
			}
			set
			{
				if ((this._huong_dan_su_dung != value))
				{
					this.Onhuong_dan_su_dungChanging(value);
					this.SendPropertyChanging();
					this._huong_dan_su_dung = value;
					this.SendPropertyChanged("huong_dan_su_dung");
					this.Onhuong_dan_su_dungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bao_quan", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string bao_quan
		{
			get
			{
				return this._bao_quan;
			}
			set
			{
				if ((this._bao_quan != value))
				{
					this.Onbao_quanChanging(value);
					this.SendPropertyChanging();
					this._bao_quan = value;
					this.SendPropertyChanged("bao_quan");
					this.Onbao_quanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia_mua", DbType="Decimal(18,0) NOT NULL")]
		public decimal gia_mua
		{
			get
			{
				return this._gia_mua;
			}
			set
			{
				if ((this._gia_mua != value))
				{
					this.Ongia_muaChanging(value);
					this.SendPropertyChanging();
					this._gia_mua = value;
					this.SendPropertyChanged("gia_mua");
					this.Ongia_muaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia_ban", DbType="Decimal(18,0) NOT NULL")]
		public decimal gia_ban
		{
			get
			{
				return this._gia_ban;
			}
			set
			{
				if ((this._gia_ban != value))
				{
					this.Ongia_banChanging(value);
					this.SendPropertyChanging();
					this._gia_ban = value;
					this.SendPropertyChanged("gia_ban");
					this.Ongia_banChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia_khuyen_mai", DbType="Decimal(18,0) NOT NULL")]
		public decimal gia_khuyen_mai
		{
			get
			{
				return this._gia_khuyen_mai;
			}
			set
			{
				if ((this._gia_khuyen_mai != value))
				{
					this.Ongia_khuyen_maiChanging(value);
					this.SendPropertyChanging();
					this._gia_khuyen_mai = value;
					this.SendPropertyChanged("gia_khuyen_mai");
					this.Ongia_khuyen_maiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong", DbType="Int NOT NULL")]
		public int so_luong
		{
			get
			{
				return this._so_luong;
			}
			set
			{
				if ((this._so_luong != value))
				{
					this.Onso_luongChanging(value);
					this.SendPropertyChanging();
					this._so_luong = value;
					this.SendPropertyChanged("so_luong");
					this.Onso_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhanh", DbType="VarChar(255)")]
		public string hinhanh
		{
			get
			{
				return this._hinhanh;
			}
			set
			{
				if ((this._hinhanh != value))
				{
					this.OnhinhanhChanging(value);
					this.SendPropertyChanging();
					this._hinhanh = value;
					this.SendPropertyChanged("hinhanh");
					this.OnhinhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanphammoi", DbType="TinyInt")]
		public System.Nullable<byte> sanphammoi
		{
			get
			{
				return this._sanphammoi;
			}
			set
			{
				if ((this._sanphammoi != value))
				{
					this.OnsanphammoiChanging(value);
					this.SendPropertyChanging();
					this._sanphammoi = value;
					this.SendPropertyChanged("sanphammoi");
					this.OnsanphammoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noibat", DbType="TinyInt")]
		public System.Nullable<byte> noibat
		{
			get
			{
				return this._noibat;
			}
			set
			{
				if ((this._noibat != value))
				{
					this.OnnoibatChanging(value);
					this.SendPropertyChanging();
					this._noibat = value;
					this.SendPropertyChanged("noibat");
					this.OnnoibatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="TinyInt NOT NULL")]
		public byte trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this.OntrangthaiChanging(value);
					this.SendPropertyChanging();
					this._trangthai = value;
					this.SendPropertyChanged("trangthai");
					this.OntrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_cap_nhap", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_cap_nhap
		{
			get
			{
				return this._ngay_cap_nhap;
			}
			set
			{
				if ((this._ngay_cap_nhap != value))
				{
					this.Onngay_cap_nhapChanging(value);
					this.SendPropertyChanging();
					this._ngay_cap_nhap = value;
					this.SendPropertyChanged("ngay_cap_nhap");
					this.Onngay_cap_nhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSanPham_tblChiTietDonHang", Storage="_tblChiTietDonHangs", ThisKey="id_sanpham", OtherKey="id_sanpham")]
		public EntitySet<tblChiTietDonHang> tblChiTietDonHangs
		{
			get
			{
				return this._tblChiTietDonHangs;
			}
			set
			{
				this._tblChiTietDonHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSanPham_tblGioHang", Storage="_tblGioHangs", ThisKey="id_sanpham", OtherKey="id_sanpham")]
		public EntitySet<tblGioHang> tblGioHangs
		{
			get
			{
				return this._tblGioHangs;
			}
			set
			{
				this._tblGioHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDanhMuc_tblSanPham", Storage="_tblDanhMuc", ThisKey="id_danhmuc", OtherKey="id_danhmuc", IsForeignKey=true)]
		public tblDanhMuc tblDanhMuc
		{
			get
			{
				return this._tblDanhMuc.Entity;
			}
			set
			{
				tblDanhMuc previousValue = this._tblDanhMuc.Entity;
				if (((previousValue != value) 
							|| (this._tblDanhMuc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblDanhMuc.Entity = null;
						previousValue.tblSanPhams.Remove(this);
					}
					this._tblDanhMuc.Entity = value;
					if ((value != null))
					{
						value.tblSanPhams.Add(this);
						this._id_danhmuc = value.id_danhmuc;
					}
					else
					{
						this._id_danhmuc = default(int);
					}
					this.SendPropertyChanged("tblDanhMuc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblThuongHieu_tblSanPham", Storage="_tblThuongHieu", ThisKey="id_thuonghieu", OtherKey="id_thuonghieu", IsForeignKey=true)]
		public tblThuongHieu tblThuongHieu
		{
			get
			{
				return this._tblThuongHieu.Entity;
			}
			set
			{
				tblThuongHieu previousValue = this._tblThuongHieu.Entity;
				if (((previousValue != value) 
							|| (this._tblThuongHieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblThuongHieu.Entity = null;
						previousValue.tblSanPhams.Remove(this);
					}
					this._tblThuongHieu.Entity = value;
					if ((value != null))
					{
						value.tblSanPhams.Add(this);
						this._id_thuonghieu = value.id_thuonghieu;
					}
					else
					{
						this._id_thuonghieu = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblThuongHieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblChiTietDonHangs(tblChiTietDonHang entity)
		{
			this.SendPropertyChanging();
			entity.tblSanPham = this;
		}
		
		private void detach_tblChiTietDonHangs(tblChiTietDonHang entity)
		{
			this.SendPropertyChanging();
			entity.tblSanPham = null;
		}
		
		private void attach_tblGioHangs(tblGioHang entity)
		{
			this.SendPropertyChanging();
			entity.tblSanPham = this;
		}
		
		private void detach_tblGioHangs(tblGioHang entity)
		{
			this.SendPropertyChanging();
			entity.tblSanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSlider")]
	public partial class tblSlider : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_slider;
		
		private string _link;
		
		private string _mo_ta_1;
		
		private string _mo_ta_2;
		
		private string _ghichu;
		
		private byte _trangthai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_sliderChanging(int value);
    partial void Onid_sliderChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    partial void Onmo_ta_1Changing(string value);
    partial void Onmo_ta_1Changed();
    partial void Onmo_ta_2Changing(string value);
    partial void Onmo_ta_2Changed();
    partial void OnghichuChanging(string value);
    partial void OnghichuChanged();
    partial void OntrangthaiChanging(byte value);
    partial void OntrangthaiChanged();
    #endregion
		
		public tblSlider()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_slider", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_slider
		{
			get
			{
				return this._id_slider;
			}
			set
			{
				if ((this._id_slider != value))
				{
					this.Onid_sliderChanging(value);
					this.SendPropertyChanging();
					this._id_slider = value;
					this.SendPropertyChanged("id_slider");
					this.Onid_sliderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="VarChar(255)")]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this.OnlinkChanging(value);
					this.SendPropertyChanging();
					this._link = value;
					this.SendPropertyChanged("link");
					this.OnlinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_ta_1", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string mo_ta_1
		{
			get
			{
				return this._mo_ta_1;
			}
			set
			{
				if ((this._mo_ta_1 != value))
				{
					this.Onmo_ta_1Changing(value);
					this.SendPropertyChanging();
					this._mo_ta_1 = value;
					this.SendPropertyChanged("mo_ta_1");
					this.Onmo_ta_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_ta_2", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string mo_ta_2
		{
			get
			{
				return this._mo_ta_2;
			}
			set
			{
				if ((this._mo_ta_2 != value))
				{
					this.Onmo_ta_2Changing(value);
					this.SendPropertyChanging();
					this._mo_ta_2 = value;
					this.SendPropertyChanged("mo_ta_2");
					this.Onmo_ta_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghichu", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string ghichu
		{
			get
			{
				return this._ghichu;
			}
			set
			{
				if ((this._ghichu != value))
				{
					this.OnghichuChanging(value);
					this.SendPropertyChanging();
					this._ghichu = value;
					this.SendPropertyChanged("ghichu");
					this.OnghichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="TinyInt NOT NULL")]
		public byte trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this.OntrangthaiChanging(value);
					this.SendPropertyChanging();
					this._trangthai = value;
					this.SendPropertyChanged("trangthai");
					this.OntrangthaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblThuongHieu")]
	public partial class tblThuongHieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_thuonghieu;
		
		private string _ten_thuonghieu;
		
		private string _meta_name;
		
		private string _link_logo;
		
		private byte _trang_thai;
		
		private EntitySet<tblSanPham> _tblSanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_thuonghieuChanging(int value);
    partial void Onid_thuonghieuChanged();
    partial void Onten_thuonghieuChanging(string value);
    partial void Onten_thuonghieuChanged();
    partial void Onmeta_nameChanging(string value);
    partial void Onmeta_nameChanged();
    partial void Onlink_logoChanging(string value);
    partial void Onlink_logoChanged();
    partial void Ontrang_thaiChanging(byte value);
    partial void Ontrang_thaiChanged();
    #endregion
		
		public tblThuongHieu()
		{
			this._tblSanPhams = new EntitySet<tblSanPham>(new Action<tblSanPham>(this.attach_tblSanPhams), new Action<tblSanPham>(this.detach_tblSanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_thuonghieu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_thuonghieu
		{
			get
			{
				return this._id_thuonghieu;
			}
			set
			{
				if ((this._id_thuonghieu != value))
				{
					this.Onid_thuonghieuChanging(value);
					this.SendPropertyChanging();
					this._id_thuonghieu = value;
					this.SendPropertyChanged("id_thuonghieu");
					this.Onid_thuonghieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_thuonghieu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ten_thuonghieu
		{
			get
			{
				return this._ten_thuonghieu;
			}
			set
			{
				if ((this._ten_thuonghieu != value))
				{
					this.Onten_thuonghieuChanging(value);
					this.SendPropertyChanging();
					this._ten_thuonghieu = value;
					this.SendPropertyChanged("ten_thuonghieu");
					this.Onten_thuonghieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_meta_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string meta_name
		{
			get
			{
				return this._meta_name;
			}
			set
			{
				if ((this._meta_name != value))
				{
					this.Onmeta_nameChanging(value);
					this.SendPropertyChanging();
					this._meta_name = value;
					this.SendPropertyChanged("meta_name");
					this.Onmeta_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link_logo", DbType="VarChar(255)")]
		public string link_logo
		{
			get
			{
				return this._link_logo;
			}
			set
			{
				if ((this._link_logo != value))
				{
					this.Onlink_logoChanging(value);
					this.SendPropertyChanging();
					this._link_logo = value;
					this.SendPropertyChanged("link_logo");
					this.Onlink_logoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="TinyInt NOT NULL")]
		public byte trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblThuongHieu_tblSanPham", Storage="_tblSanPhams", ThisKey="id_thuonghieu", OtherKey="id_thuonghieu")]
		public EntitySet<tblSanPham> tblSanPhams
		{
			get
			{
				return this._tblSanPhams;
			}
			set
			{
				this._tblSanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblSanPhams(tblSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tblThuongHieu = this;
		}
		
		private void detach_tblSanPhams(tblSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tblThuongHieu = null;
		}
	}
}
#pragma warning restore 1591
